### ISSUE TITLE
XML - add support for escape sequences

### ISSUE THREAD

**Issue by Sasino97** [Relfos/lunar_parser#12]
I suggest to add support for these escapes:
```xml
<    &lt;
>    &gt;
&    &amp;
"    &quot;
'    &apos;
```

**Comment by Relfos** [comment]
Thanks for the request, it is now done, commit 68b8d51c1b8b29acd05bf60f9fb42ea02d255416.

Also uploaded the new build to Nuget, package version 1.54.
