### ISSUE TITLE
CDATA multi-line issue

### ISSUE THREAD

**Issue by dodaeche** [Relfos/lunar_parser#6]
Thanks for your [fix for CDATA error](https://github.com/Relfos/lunar_parser/commit/248ed42512d86c839c3b1516bafa3c041af99ba0). I tried again with fix and found another issue.
If I use multi-line strings in CDATA tag, Parser removes '\r\n' and make all-in-one line strings.

            string test = String.Format(@"
                                <message>
                                    <content><![CDATA[
                                       line1.test<>me
                                       line2.hello
                                       ]]>
                                    </content>
                                </message>");

            var root = XMLReader.ReadFromString(test);
            var msg = root["message"];
            var content = msg.GetString("content");
            Console.WriteLine("Message: " + content);
Except : "line1.test<>me\r\nline2.hello\r\n"
Result : "line1.test<>meline2.hello\r\n"

thanks again for your work.

**Comment by Relfos** [comment]
Ok, bug fixed, all whitespace is now preserved inside CDATA.
Thanks again for reporting the issue!
